/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{

	//	//Create Pointer pointing to above address; (don't forget to type cast the address otherwise it will considered as integer value to pointers)p	uintmax_t *ptrClkRccReg = (uintmax_t*) 0x40023830;
	uintmax_t *ptrClkRccReg = (uintmax_t*) 0x40023830;
	uintmax_t *ptrModeReg = (uintmax_t*) 0x40020c00;
	uintmax_t *ptrOutputDataReg = (uintmax_t*) 0x40020c14;

	uintmax_t *ptrModeInputReg = (uintmax_t*) 0x40020c00;
	uintmax_t *ptrInputDataReg = (uintmax_t*) 0x40020c10;
	uintmax_t statusReg;



	//1. SET RCC 3rd Bit position for GPIOD
	*ptrClkRccReg |= (0x1<<3);   //-> (mask value) has been calculated by Left shifting 0x1<<3; why shifting with 3 bcz it is asked to SET 3rd bit position of CLK RCC registers



	//2. SETING Mode Register at Pin-12
		//-> Firstly, CLEAR 25th and 24th bit to 0,0 -> for CLEARING (&) and Mask value -> calculate through left shift (all 1s except 25th and 24th position is 0).
		//-> Then, SEt 25th and 24th bit to 0,1 -> for SETTING (|) and the Mask Value ->calculate through left shift (all 0s except 25-> 0 & 24-> 1)

	*ptrModeReg &= ~(0x3<<24);  //CLEARING(& *), Mask value -> left shift binary 0000....011=hex 0x3;  0x3<<24 and then negating to 111..00111...1
	*ptrModeReg |= 0x1<<24;		//SETTING(| +), Mask Value -> left shift binary 000...001=hex 0x1;  0x1<<24


	*ptrModeInputReg &= ~(3<<0); //CLEARING(1st and 2nd Bit) 1st pin, rest bit unchanged and enabling 00->input moder, mask value-> 0xfffffffc (1111..0011)


	while(1){

//		reading port_d pin-1 status, this will grap the status of of pin 1 to check if it is connected to VCC(1) or GND(0).
		statusReg = (uintmax_t) *ptrInputDataReg & 0x2;

		if (statusReg){

			*ptrOutputDataReg |= (0x1<<12);

		}

		else{
			*ptrOutputDataReg &= ~(0x1<<12);
		}

	}



//	/* Loop forever */
//	while(1);

}
